config/routes.rb
Rails.application.routes.draw do
  resources :clients
  resources :pet_histories
  resources :pets
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "pets#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/client.rb
class Client < ApplicationRecord
    has_many :pets
    def petsCount
        self.pets.count
    end
end

app/models/pet.rb
class Pet < ApplicationRecord

  has_many :pet_histories
  belongs_to :client

  def historyCount
    self.pet_histories.count
  end

  def avgWeight
    self.pet_histories.average(:weight)
  end

  def avgHeight
    self.pet_histories.average(:heigth)
  end

  def maxWeight
    self.pet_histories.pluck(:weight).max
  end

  def maxHeight
    self.pet_histories.pluck(:heigth).max
  end

end

app/models/pet_history.rb
class PetHistory < ApplicationRecord
        belongs_to :pet
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: %i[ show edit update destroy ]

  # GET /clients or /clients.json
  def index
    @clients = Client.all
  end

  # GET /clients/1 or /clients/1.json
  def show
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients or /clients.json
  def create
    @client = Client.new(client_params)

    respond_to do |format|
      if @client.save
        format.html { redirect_to @client, notice: "Client was successfully created." }
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1 or /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to @client, notice: "Client was successfully updated." }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1 or /clients/1.json
  def destroy
    @client.destroy
    respond_to do |format|
      format.html { redirect_to clients_url, notice: "Client was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def client_params
      params.require(:client).permit(:name, :phone, :email)
    end
end

app/controllers/pet_histories_controller.rb
class PetHistoriesController < ApplicationController
  before_action :set_pet_history, only: [:show, :edit, :update, :destroy]

  # GET /pet_histories
  # GET /pet_histories.json
  def index
    @pet_histories = PetHistory.all
  end

  # GET /pet_histories/1
  # GET /pet_histories/1.json
  def show
  end

  # GET /pet_histories/new
  def new
    @pet_history = PetHistory.new
    @pets = Pet.pluck :name, :id
  end

  # GET /pet_histories/1/edit
  def edit
    @pets = Pet.pluck :name, :id
  end

  # POST /pet_histories
  # POST /pet_histories.json
  def create
    @pet_history = PetHistory.new(pet_history_params)

    respond_to do |format|
      if @pet_history.save
        format.html { redirect_to @pet_history, notice: 'Pet history was successfully created.' }
        format.json { render :show, status: :created, location: @pet_history }
      else
        format.html { render :new }
        format.json { render json: @pet_history.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pet_histories/1
  # PATCH/PUT /pet_histories/1.json
  def update
    respond_to do |format|
      if @pet_history.update(pet_history_params)
        format.html { redirect_to @pet_history, notice: 'Pet history was successfully updated.' }
        format.json { render :show, status: :ok, location: @pet_history }
      else
        format.html { render :edit }
        format.json { render json: @pet_history.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pet_histories/1
  # DELETE /pet_histories/1.json
  def destroy
    @pet_history.destroy
    respond_to do |format|
      format.html { redirect_to pet_histories_url, notice: 'Pet history was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pet_history
      @pet_history = PetHistory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pet_history_params
      params.require(:pet_history).permit(:weight, :heigth, :description, :pet_id)
    end
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  before_action :set_pet, only: [:show, :edit, :update, :destroy]

  # GET /pets
  # GET /pets.json
  def index
    @pets = Pet.all
  end

  # GET /pets/1
  # GET /pets/1.json
  def show
  end

  # GET /pets/new
  def new
    @pet = Pet.new
    @clients = Client.pluck :name, :id
  end

  # GET /pets/1/edit
  def edit
    @clients = Client.pluck :name, :id 
  end

  # POST /pets
  # POST /pets.json
  def create
    @pet = Pet.new(pet_params)

    respond_to do |format|
      if @pet.save
        format.html { redirect_to @pet, notice: 'Pet was successfully created.' }
        format.json { render :show, status: :created, location: @pet }
      else
        format.html { render :new }
        format.json { render json: @pet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pets/1
  # PATCH/PUT /pets/1.json
  def update
    respond_to do |format|
      if @pet.update(pet_params)
        format.html { redirect_to @pet, notice: 'Pet was successfully updated.' }
        format.json { render :show, status: :ok, location: @pet }
      else
        format.html { render :edit }
        format.json { render json: @pet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pets/1
  # DELETE /pets/1.json
  def destroy
    @pet.destroy
    respond_to do |format|
      format.html { redirect_to pets_url, notice: 'Pet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pet
      @pet = Pet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pet_params
      params.require(:pet).permit(:name, :breed, :birthdate, :client_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/pet_histories_helper.rb
module PetHistoriesHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/views/clients/_form.html.erb
<%= form_with(model: client, local: true) do |form| %>
  <% if client.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(client.errors.count, "error") %> prohibited this client from being saved:</h2>

      <ul>
      <% client.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.text_field :phone %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/clients/edit.html.erb
<h1>Editing Client</h1>

<%= render 'form', client: @client %>

<%= link_to 'Show', @client %> |
<%= link_to 'Back', clients_path %>

app/views/clients/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Clients</h1>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>Name</th>
      <th>Phone</th>
      <th>Email</th>
      <th>Pets</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @clients.each do |client| %>
      <tr>
        <td><%= client.name %></td>
        <td><%= client.phone %></td>
        <td><%= client.email %></td>
        <td><%= client.petsCount %></td>
        <td><%= link_to 'Show', client %></td>
        <td><%= link_to 'Edit', edit_client_path(client) %></td>
        <td><%= link_to 'Destroy', client, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Client', new_client_path %>

app/views/clients/new.html.erb
<h1>New Client</h1>

<%= render 'form', client: @client %>

<%= link_to 'Back', clients_path %>

app/views/clients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @client.name %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @client.phone %>
</p>

<p>
  <strong>Email:</strong>
  <%= @client.email %>
</p>

  
<%= link_to 'Edit', edit_client_path(@client) %> |
<%= link_to 'Back', clients_path %>

<h2>Pets</h2>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>Name</th>
      <th>Max Weight</th>
      <th>Max Height</th>
    </tr>
  </thead>
  <tbody>
  <% @client.pets.each do |pet|%>
    <tr> 
    <td> <%= pet.name %> </td> 
    <td><%= pet.maxHeight %></td> 
    <td><%= pet.maxWeight %></td> 
    </tr>
  <% end %>
  </tbody>
  </table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Unit7ChallengeVet</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Menu</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <%= link_to "Pets",root_path, :class=>"nav-link" %>
      </li>
      <li class="nav-item">
                <%= link_to "Pets Histories",pet_histories_path, :class=>"nav-link" %>
      </li>
      <li class="nav-item">
                <%= link_to "Clients",clients_path, :class=>"nav-link" %>
      </li>
    </ul>
  </div>
</nav>
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>
    <%= yield %>
  </body>
</html>

app/views/pet_histories/_form.html.erb
<%= form_with(model: pet_history, local: true) do |form| %>
  <% if pet_history.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pet_history.errors.count, "error") %> prohibited this pet_history from being saved:</h2>

      <ul>
      <% pet_history.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= form.label :pet_id %>
    <%= form.text_field :pet_id %>
    <%= form.select :pet_id, options_for_select(@pets)%>
    
  </div>

  <div class="field">
    <%= form.label :weight %>
    <%= form.text_field :weight %>
  </div>

  <div class="field">
    <%= form.label :heigth %>
    <%= form.text_field :heigth %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pet_histories/edit.html.erb
<h1>Editing Pet History</h1>

<%= render 'form', pet_history: @pet_history %>

<%= link_to 'Show', @pet_history %> |
<%= link_to 'Back', pet_histories_path %>

app/views/pet_histories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pet Histories</h1>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>Weight</th>
      <th>Heigth</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pet_histories.each do |pet_history| %>
      <tr>
        <td><%= pet_history.weight %></td>
        <td><%= pet_history.heigth %></td>
        <td><%= pet_history.description %></td>
        <td><%= link_to 'Show', pet_history %></td>
        <td><%= link_to 'Edit', edit_pet_history_path(pet_history) %></td>
        <td><%= link_to 'Destroy', pet_history, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pet History', new_pet_history_path %>

app/views/pet_histories/new.html.erb
<h1>New Pet History</h1>

<%= render 'form', pet_history: @pet_history %>

<%= link_to 'Back', pet_histories_path %>

app/views/pet_histories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Weight:</strong>
  <%= @pet_history.weight %>
</p>

<p>
  <strong>Heigth:</strong>
  <%= @pet_history.heigth %>
</p>

<p>
  <strong>Description:</strong>
  <%= @pet_history.description %>
</p>

<%= link_to 'Edit', edit_pet_history_path(@pet_history) %> |
<%= link_to 'Back', pet_histories_path %>

app/views/pets/_form.html.erb
<%= form_with(model: pet, local: true) do |form| %>
  <% if pet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pet.errors.count, "error") %> prohibited this pet from being saved:</h2>

      <ul>
      <% pet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :client_id %>
    <%= form.select :client_id, options_for_select(@clients) %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :breed %>
    <%= form.text_field :breed %>
  </div>

  <div class="field">
    <%= form.label :birthdate %>
    <%= form.date_select :birthdate %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pets/edit.html.erb
<h1>Editing Pet</h1>

<%= render 'form', pet: @pet %>

<%= link_to 'Show', @pet %> |
<%= link_to 'Back', pets_path %>

app/views/pets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pets</h1>
<div class=container>
  <table class="table table-bordered">
    <thead>
      <tr>
        <th>Name</th>
        <th>Breed</th>
        <th>Birthdate</th>
        <th>Visitas</th>
        <th>History</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @pets.each do |pet| %>
        <tr>
          <td><%= pet.name %></td>
          <td><%= pet.breed %></td>
          <td><%= pet.birthdate %></td>
          <td><%= pet.historyCount%></td>
            <td>
    <table class="table table-bordered">
      <thead>
        <tr>
          <th>Weight</th>
          <th>Heigth</th>
          <th>Description</th>
        </tr>
      </thead>

    <tbody>
        <% pet.pet_histories.each do |pet_history| %>
          <tr>
            <td><%= pet_history.weight %></td>
            <td><%= pet_history.heigth %></td>
            <td><%= pet_history.description %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
          <td><%= link_to 'Show', pet %></td>
          <td><%= link_to 'Edit', edit_pet_path(pet) %></td>
          <td><%= link_to 'Destroy', pet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Pet', new_pet_path %>
</div>

app/views/pets/new.html.erb
<h1>New Pet</h1>

<%= render 'form', pet: @pet %>

<%= link_to 'Back', pets_path %>

app/views/pets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @pet.name %>
</p>

<p>
  <strong>Breed:</strong>
  <%= @pet.breed %>
</p>

<p>
  <strong>Birthdate:</strong>
  <%= @pet.birthdate %>
</p>
<p>
  <strong>Visits:</strong>
  <%= @pet.historyCount %>
</p>
<div class="container">
  <h1>History</h1>
  <table class="table table-bordered">
        <thead>
          <tr>
            <th>Weight</th>
            <th>Heigth</th>
            <th>Description</th>
          </tr>
        </thead>

      <tbody>
          <% @pet.pet_histories.each do |pet_history| %>
            <tr>
              <td><%= pet_history.weight %></td>
              <td><%= pet_history.heigth %></td>
              <td><%= pet_history.description %></td>
            </tr>
          <% end %>
        </tbody>
  </table>
  <h1>Datos</h1>
  <table class="table table-bordered">
    <thead>
      <tr>
        <th>Peso promedio</th>
        <th>Altura promedio</th>
        <th>Peso Máximo</th>
        <th>Altura Máxima</th>
      </tr>
    </thead>
      
    <tbody>
      <tr>
        <td><%= @pet.avgWeight %></td>
        <td><%= @pet.avgHeight %></td>
        <td><%= @pet.maxWeight %></td>
        <td><%= @pet.maxHeight%></td>
      </tr>
    </tbody>
  </table>

  <%= link_to 'Edit', edit_pet_path(@pet) %> |
  <%= link_to 'Back', pets_path %>
</div>